var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":154,"id":3240,"methods":[{"el":57,"sc":2,"sl":53},{"el":111,"sc":2,"sl":81},{"el":150,"sc":2,"sl":135}],"name":"AuthorizationTicketCertGenerator","sl":39}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_142":{"methods":[{"sl":81}],"name":"Verify that illegal argument exception is thrown for messages with unsupported subject type","pass":true,"statements":[{"sl":94},{"sl":109}]},"test_182":{"methods":[{"sl":135}],"name":"Generate Authorization Credential with a certificate chain as signer info","pass":true,"statements":[{"sl":148},{"sl":149}]},"test_365":{"methods":[{"sl":81}],"name":"Generate Authorization Ticket with a certificate as signer info","pass":true,"statements":[{"sl":94},{"sl":95},{"sl":96},{"sl":97},{"sl":107}]},"test_392":{"methods":[{"sl":53},{"sl":81}],"name":"Generate Authorization Ticket and Signed Secured Message v1 for interoperability testing","pass":true,"statements":[{"sl":54},{"sl":55},{"sl":56},{"sl":94},{"sl":95},{"sl":96},{"sl":99},{"sl":100},{"sl":101},{"sl":107}]},"test_90":{"methods":[{"sl":81}],"name":"Generate Authorization Ticket with a digest as signer info","pass":true,"statements":[{"sl":94},{"sl":95},{"sl":96},{"sl":99},{"sl":100},{"sl":101},{"sl":107}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [392], [392], [392], [392], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [142, 392, 90, 365], [], [], [], [], [], [], [], [], [], [], [], [], [142, 392, 90, 365], [392, 90, 365], [392, 90, 365], [365], [], [392, 90], [392, 90], [392, 90], [], [], [], [], [], [392, 90, 365], [], [142], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [182], [], [], [], [], [], [], [], [], [], [], [], [], [182], [182], [], [], [], [], []]
