var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":64,"id":13173,"methods":[{"el":45,"sc":2,"sl":30},{"el":62,"sc":2,"sl":47}],"name":"SubjectAttributeTypeSpec","sl":28}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_10":{"methods":[{"sl":30}],"name":"Verify that assurance_level has bytevalue 2","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_192":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns assurance_level for 2","pass":true,"statements":[{"sl":50}]},"test_341":{"methods":[{"sl":30}],"name":"Verify that reconstruction_value has bytevalue 3","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_369":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns its_aid_list for 32","pass":true,"statements":[{"sl":50}]},"test_413":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns encryption_key for 1","pass":true,"statements":[{"sl":50}]},"test_654":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns its_aid_ssp_list for 33","pass":true,"statements":[{"sl":50}]},"test_690":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns verification_key for 0","pass":true,"statements":[{"sl":50}]},"test_777":{"methods":[{"sl":30}],"name":"Verify that its_aid_ssp_list has bytevalue 33","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_812":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns priority_its_aid_list for 34","pass":true,"statements":[{"sl":50}]},"test_831":{"methods":[{"sl":30}],"name":"Verify that verification_key has bytevalue 0","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_849":{"methods":[{"sl":30}],"name":"Verify that its_aid_list has bytevalue 32","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_866":{"methods":[{"sl":30}],"name":"Verify that priority_its_aid_list has bytevalue 34","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_980":{"methods":[{"sl":30}],"name":"Verify that priority_ssp_list has bytevalue 35","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_986":{"methods":[{"sl":30}],"name":"Verify that encryption_key has bytevalue 1","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_993":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns priority_ssp_list for 35","pass":true,"statements":[{"sl":50}]},"test_996":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns reconstruction_value for 3","pass":true,"statements":[{"sl":50}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [341, 866, 777, 849, 980, 986, 10, 831], [], [], [341, 866, 777, 849, 980, 986, 10, 831], [341, 866, 777, 849, 980, 986, 10, 831], [], [], [], [], [], [], [], [], [], [], [], [], [690, 192, 812, 369, 996, 654, 993, 413], [], [], [690, 192, 812, 369, 996, 654, 993, 413], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
