var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":64,"id":4012,"methods":[{"el":45,"sc":2,"sl":30},{"el":62,"sc":2,"sl":47}],"name":"SubjectAttributeTypeSpec","sl":28}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_102":{"methods":[{"sl":30}],"name":"Verify that its_aid_list has bytevalue 32","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_155":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns its_aid_list for 32","pass":true,"statements":[{"sl":50}]},"test_162":{"methods":[{"sl":30}],"name":"Verify that reconstruction_value has bytevalue 3","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_173":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns priority_its_aid_list for 34","pass":true,"statements":[{"sl":50}]},"test_188":{"methods":[{"sl":30}],"name":"Verify that its_aid_ssp_list has bytevalue 33","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_206":{"methods":[{"sl":30}],"name":"Verify that priority_ssp_list has bytevalue 35","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_210":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns reconstruction_value for 3","pass":true,"statements":[{"sl":50}]},"test_214":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns priority_ssp_list for 35","pass":true,"statements":[{"sl":50}]},"test_246":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns encryption_key for 1","pass":true,"statements":[{"sl":50}]},"test_257":{"methods":[{"sl":30}],"name":"Verify that priority_its_aid_list has bytevalue 34","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_294":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns assurance_level for 2","pass":true,"statements":[{"sl":50}]},"test_306":{"methods":[{"sl":30}],"name":"Verify that assurance_level has bytevalue 2","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_377":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns verification_key for 0","pass":true,"statements":[{"sl":50}]},"test_404":{"methods":[{"sl":30}],"name":"Verify that encryption_key has bytevalue 1","pass":true,"statements":[{"sl":33},{"sl":34}]},"test_405":{"methods":[{"sl":47}],"name":"Verify that SubjectAttributeType.getByValue returns its_aid_ssp_list for 33","pass":true,"statements":[{"sl":50}]},"test_61":{"methods":[{"sl":30}],"name":"Verify that verification_key has bytevalue 0","pass":true,"statements":[{"sl":33},{"sl":34}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [162, 206, 257, 404, 61, 102, 188, 306], [], [], [162, 206, 257, 404, 61, 102, 188, 306], [162, 206, 257, 404, 61, 102, 188, 306], [], [], [], [], [], [], [], [], [], [], [], [], [210, 155, 294, 246, 405, 377, 173, 214], [], [], [210, 155, 294, 246, 405, 377, 173, 214], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
