var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":50,"id":4321,"methods":[{"el":36,"sc":2,"sl":35},{"el":43,"sc":2,"sl":41},{"el":48,"sc":2,"sl":45}],"name":"PreSharedKeyRecipientInfo","sl":27}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_240":{"methods":[{"sl":35}],"name":"Verify that SequenceOfRecipientInfo is initialized properly","pass":true,"statements":[]},"test_286":{"methods":[{"sl":41}],"name":"Verify that preshared key encryption works correctly","pass":true,"statements":[{"sl":42}]},"test_289":{"methods":[{"sl":45}],"name":"Verify toString","pass":true,"statements":[{"sl":47}]},"test_396":{"methods":[{"sl":35}],"name":"Verify that constructor and getters are correct and it is correctly encoded","pass":true,"statements":[]},"test_400":{"methods":[{"sl":35}],"name":"Verify that RecipientInfo is correctly encoded for type pskRecipInfo","pass":true,"statements":[]},"test_413":{"methods":[{"sl":41}],"name":"Verify that fullfillsRequirements verifies all required fields","pass":true,"statements":[{"sl":42}]},"test_460":{"methods":[{"sl":35}],"name":"Verify that  Ieee1609Dot2Content is correctly encoded for type encryptedData","pass":true,"statements":[]},"test_538":{"methods":[{"sl":41},{"sl":45}],"name":"Verify toString","pass":true,"statements":[{"sl":42},{"sl":47}]},"test_693":{"methods":[{"sl":41}],"name":"Verify that fullfillsRequirements verifies all required fields","pass":true,"statements":[{"sl":42}]},"test_782":{"methods":[{"sl":35},{"sl":41}],"name":"Verify that constructor and getters are correct and it is correctly encoded","pass":true,"statements":[{"sl":42}]},"test_930":{"methods":[{"sl":45}],"name":"Verify toString","pass":true,"statements":[{"sl":47}]},"test_943":{"methods":[{"sl":45}],"name":"Verify EncryptedDataEncryptionKey","pass":true,"statements":[{"sl":47}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [782, 240, 460, 396, 400], [], [], [], [], [], [782, 538, 286, 413, 693], [782, 538, 286, 413, 693], [], [], [538, 930, 943, 289], [], [538, 930, 943, 289], [], [], []]
