var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":68,"id":11170,"methods":[{"el":48,"sc":2,"sl":31},{"el":66,"sc":2,"sl":50}],"name":"HeaderFieldTypeSpec","sl":29}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_112":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns expiration for 2","pass":true,"statements":[{"sl":53}]},"test_216":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns message_type for 5","pass":true,"statements":[{"sl":53}]},"test_231":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns signer_info for 128","pass":true,"statements":[{"sl":53}]},"test_264":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_location for 3","pass":true,"statements":[{"sl":53}]},"test_297":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns encryption_parameters for 130","pass":true,"statements":[{"sl":53}]},"test_380":{"methods":[{"sl":31}],"name":"Verify that request_unrecognized_certificate has bytevalue 4","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_407":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_time for 0","pass":true,"statements":[{"sl":53}]},"test_472":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns recipient_info for 129","pass":true,"statements":[{"sl":53}]},"test_561":{"methods":[{"sl":31}],"name":"Verify that expiration has bytevalue 2","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_643":{"methods":[{"sl":31}],"name":"Verify that recipient_info has bytevalue 129","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_675":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_time_confidence for 1","pass":true,"statements":[{"sl":53}]},"test_717":{"methods":[{"sl":31}],"name":"Verify that generation_time_confidence has bytevalue 1","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_743":{"methods":[{"sl":31}],"name":"Verify that generation_location has bytevalue 3","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_744":{"methods":[{"sl":31}],"name":"Verify that generation_time has bytevalue 0","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_790":{"methods":[{"sl":31}],"name":"Verify that message_type has bytevalue 5","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_864":{"methods":[{"sl":31}],"name":"Verify that encryption_parameters has bytevalue 130","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_866":{"methods":[{"sl":31}],"name":"Verify that signer_info has bytevalue 128","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_935":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns request_unrecognized_certificate for 4","pass":true,"statements":[{"sl":53}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [744, 380, 866, 561, 864, 790, 643, 717, 743], [], [], [744, 380, 866, 561, 864, 790, 643, 717, 743], [744, 380, 866, 561, 864, 790, 643, 717, 743], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [675, 297, 216, 407, 112, 231, 935, 264, 472], [], [], [675, 297, 216, 407, 112, 231, 935, 264, 472], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
