var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":68,"id":5602,"methods":[{"el":48,"sc":2,"sl":31},{"el":66,"sc":2,"sl":50}],"name":"HeaderFieldTypeSpec","sl":29}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_136":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns encryption_parameters for 130","pass":true,"statements":[{"sl":53}]},"test_166":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_time_confidence for 1","pass":true,"statements":[{"sl":53}]},"test_167":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns request_unrecognized_certificate for 4","pass":true,"statements":[{"sl":53}]},"test_185":{"methods":[{"sl":31}],"name":"Verify that generation_time_confidence has bytevalue 1","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_186":{"methods":[{"sl":31}],"name":"Verify that recipient_info has bytevalue 129","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_213":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_location for 3","pass":true,"statements":[{"sl":53}]},"test_241":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns signer_info for 128","pass":true,"statements":[{"sl":53}]},"test_264":{"methods":[{"sl":31}],"name":"Verify that signer_info has bytevalue 128","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_275":{"methods":[{"sl":31}],"name":"Verify that expiration has bytevalue 2","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_314":{"methods":[{"sl":31}],"name":"Verify that request_unrecognized_certificate has bytevalue 4","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_320":{"methods":[{"sl":31}],"name":"Verify that message_type has bytevalue 5","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_322":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns expiration for 2","pass":true,"statements":[{"sl":53}]},"test_337":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns message_type for 5","pass":true,"statements":[{"sl":53}]},"test_349":{"methods":[{"sl":31}],"name":"Verify that generation_location has bytevalue 3","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_38":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns recipient_info for 129","pass":true,"statements":[{"sl":53}]},"test_5":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_time for 0","pass":true,"statements":[{"sl":53}]},"test_52":{"methods":[{"sl":31}],"name":"Verify that encryption_parameters has bytevalue 130","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_53":{"methods":[{"sl":31}],"name":"Verify that generation_time has bytevalue 0","pass":true,"statements":[{"sl":34},{"sl":35}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [264, 186, 185, 349, 320, 314, 52, 275, 53], [], [], [264, 186, 185, 349, 320, 314, 52, 275, 53], [264, 186, 185, 349, 320, 314, 52, 275, 53], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [213, 322, 241, 5, 167, 166, 38, 337, 136], [], [], [213, 322, 241, 5, 167, 166, 38, 337, 136], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
