var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":68,"id":5602,"methods":[{"el":48,"sc":2,"sl":31},{"el":66,"sc":2,"sl":50}],"name":"HeaderFieldTypeSpec","sl":29}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_101":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_time for 0","pass":true,"statements":[{"sl":53}]},"test_157":{"methods":[{"sl":31}],"name":"Verify that message_type has bytevalue 5","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_174":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns encryption_parameters for 130","pass":true,"statements":[{"sl":53}]},"test_199":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_location for 3","pass":true,"statements":[{"sl":53}]},"test_215":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns recipient_info for 129","pass":true,"statements":[{"sl":53}]},"test_247":{"methods":[{"sl":31}],"name":"Verify that generation_time_confidence has bytevalue 1","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_302":{"methods":[{"sl":31}],"name":"Verify that generation_time has bytevalue 0","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_305":{"methods":[{"sl":31}],"name":"Verify that recipient_info has bytevalue 129","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_317":{"methods":[{"sl":31}],"name":"Verify that request_unrecognized_certificate has bytevalue 4","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_34":{"methods":[{"sl":31}],"name":"Verify that signer_info has bytevalue 128","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_351":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns generation_time_confidence for 1","pass":true,"statements":[{"sl":53}]},"test_352":{"methods":[{"sl":31}],"name":"Verify that generation_location has bytevalue 3","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_361":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns message_type for 5","pass":true,"statements":[{"sl":53}]},"test_407":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns signer_info for 128","pass":true,"statements":[{"sl":53}]},"test_55":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns expiration for 2","pass":true,"statements":[{"sl":53}]},"test_86":{"methods":[{"sl":31}],"name":"Verify that encryption_parameters has bytevalue 130","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_95":{"methods":[{"sl":50}],"name":"Verify that TrailerFieldType.getByValue returns request_unrecognized_certificate for 4","pass":true,"statements":[{"sl":53}]},"test_97":{"methods":[{"sl":31}],"name":"Verify that expiration has bytevalue 2","pass":true,"statements":[{"sl":34},{"sl":35}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [302, 247, 317, 157, 86, 305, 352, 34, 97], [], [], [302, 247, 317, 157, 86, 305, 352, 34, 97], [302, 247, 317, 157, 86, 305, 352, 34, 97], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [95, 199, 407, 351, 55, 215, 361, 174, 101], [], [], [95, 199, 407, 351, 55, 215, 361, 174, 101], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
