var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":55,"id":8219,"methods":[{"el":33,"sc":2,"sl":30},{"el":37,"sc":2,"sl":35},{"el":41,"sc":2,"sl":39},{"el":53,"sc":2,"sl":46}],"name":"MessageType","sl":23}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1010":{"methods":[{"sl":35},{"sl":39}],"name":"Verify that multiple payload works for version 1 of secured DENM message","pass":true,"statements":[{"sl":36},{"sl":40}]},"test_158":{"methods":[{"sl":35},{"sl":39}],"name":"Verify that multiple payload works for version 1 of secured CAM message","pass":true,"statements":[{"sl":36},{"sl":40}]},"test_308":{"methods":[{"sl":35},{"sl":39}],"name":"Verify that CAM has value 2 and security profile","pass":true,"statements":[{"sl":36},{"sl":40}]},"test_444":{"methods":[{"sl":35},{"sl":39}],"name":"Verify that DENM has value 1 and security profile","pass":true,"statements":[{"sl":36},{"sl":40}]},"test_745":{"methods":[{"sl":46}],"name":"Verify that SecurityProfile.getByValue returns CAM for 2","pass":true,"statements":[{"sl":47},{"sl":48},{"sl":49}]},"test_852":{"methods":[{"sl":35},{"sl":39}],"name":"Generate version 1 Signed CAM Message with and verify that all required fields are set and signature verifies.","pass":true,"statements":[{"sl":36},{"sl":40}]},"test_899":{"methods":[{"sl":35},{"sl":39}],"name":"Generate version 1 Signed CAM Unrecognized Certificates Message and verify that all required fields are set and signature verifies.","pass":true,"statements":[{"sl":36},{"sl":40}]},"test_90":{"methods":[{"sl":35},{"sl":39}],"name":"Generate Signed DENM Message and verify that all required fields are set and signature verifies.[0]","pass":true,"statements":[{"sl":36},{"sl":40}]},"test_947":{"methods":[{"sl":46}],"name":"Verify that SecurityProfile.getByValue returns DENM for 1","pass":true,"statements":[{"sl":47},{"sl":48},{"sl":49}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [1010, 308, 90, 899, 444, 158, 852], [1010, 308, 90, 899, 444, 158, 852], [], [], [1010, 308, 90, 899, 444, 158, 852], [1010, 308, 90, 899, 444, 158, 852], [], [], [], [], [], [947, 745], [947, 745], [947, 745], [947, 745], [], [], [], [], [], []]
