var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":60,"id":3824,"methods":[{"el":44,"sc":2,"sl":31},{"el":58,"sc":2,"sl":46}],"name":"PayloadTypeSpec","sl":29}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_101":{"methods":[{"sl":31}],"name":"Verify that signed has bytevalue 1","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_122":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns unsecured for 0","pass":true,"statements":[{"sl":49}]},"test_140":{"methods":[{"sl":31}],"name":"Verify that signed_external has bytevalue 3","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_154":{"methods":[{"sl":31}],"name":"Verify that unsecured has bytevalue 0","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_178":{"methods":[{"sl":31}],"name":"Verify that signed_and_encrypted has bytevalue 4","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_218":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns encrypted for 2","pass":true,"statements":[{"sl":49}]},"test_225":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns signed_external for 3","pass":true,"statements":[{"sl":49}]},"test_29":{"methods":[{"sl":31}],"name":"Verify that encrypted has bytevalue 2","pass":true,"statements":[{"sl":34},{"sl":35}]},"test_375":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns signed for 1","pass":true,"statements":[{"sl":49}]},"test_87":{"methods":[{"sl":46}],"name":"Verify that TrailerFieldType.getByValue returns signed_and_encrypted for 4","pass":true,"statements":[{"sl":49}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [29, 154, 101, 178, 140], [], [], [29, 154, 101, 178, 140], [29, 154, 101, 178, 140], [], [], [], [], [], [], [], [], [], [], [87, 225, 218, 122, 375], [], [], [87, 225, 218, 122, 375], [], [], [], [], [], [], [], [], [], [], []]
