var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":61,"id":2634,"methods":[{"el":36,"sc":2,"sl":34},{"el":46,"sc":2,"sl":43},{"el":53,"sc":2,"sl":51},{"el":58,"sc":2,"sl":55}],"name":"LinkageValue","sl":24}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_211":{"methods":[{"sl":34}],"name":"Verify that constructor and getters are correct and it is correctly encoded","pass":true,"statements":[{"sl":35}]},"test_325":{"methods":[{"sl":55}],"name":"Verify toString","pass":true,"statements":[{"sl":57}]},"test_431":{"methods":[{"sl":34}],"name":"Verify that IllegalArgumentException is thrown when encoding if not all fields are set","pass":true,"statements":[{"sl":35}]},"test_444":{"methods":[{"sl":43},{"sl":55}],"name":"Verify toString","pass":true,"statements":[{"sl":44},{"sl":57}]},"test_616":{"methods":[{"sl":34},{"sl":55}],"name":"Verify that reference structure from D.5.2.2 of P1909.2_D12 is parsed and regenerated correctly","pass":true,"statements":[{"sl":35},{"sl":57}]},"test_685":{"methods":[{"sl":34},{"sl":55}],"name":"Verify that it is possible to parse the reference implicit certificate","pass":true,"statements":[{"sl":35},{"sl":57}]},"test_690":{"methods":[{"sl":34},{"sl":43},{"sl":51}],"name":"Verify that LinkageValue stores the data correctly","pass":true,"statements":[{"sl":35},{"sl":44},{"sl":52}]},"test_714":{"methods":[{"sl":34}],"name":"Verify that CertificateId is correctly encoded for type linkageData","pass":true,"statements":[{"sl":35}]},"test_887":{"methods":[{"sl":34},{"sl":55}],"name":"Verify toString","pass":true,"statements":[{"sl":35},{"sl":57}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [211, 431, 690, 714, 685, 887, 616], [211, 431, 690, 714, 685, 887, 616], [], [], [], [], [], [], [], [690, 444], [690, 444], [], [], [], [], [], [], [690], [690], [], [], [325, 444, 685, 887, 616], [], [325, 444, 685, 887, 616], [], [], [], []]
